### ISSUE TITLE
Compatibility - More Pokédex Page : Size Comparison

### ISSUE THREAD

**Issue by Thobov** [FL-/Essentials-AdvancedDex#1]
Dear FL,

Your work on Advanced Dex is wonderful. Thank you for developing this script. It works perfectly when using it standalone. However, I am having compatibility issues when using Advanced Dex simultaneously with another plugin called More Pokédex Page : Size Comparison. I tried changing the values in the script.rb file but that was unsuccessful. Could you please help me getting this work or add support for it?

Resource More Pokédex Page : Size Comparison
https://www.reliccastle.com/resources/966/

Regards,
Thomas

**Comment by FL-** [comment]
You need to edit the other plugin instead of UI_Pokedex_Entry and this script. I made an update in this script today to make easier to add more pages.

Instead of changing it to '@page = 3 if @page > 3', you need to edit the other plugin script ('@page = 5 if @page > 5' in case of More Pokédex Page). In Advanced Dex script, you need to edit ADVANCED_PAGE and barBitmapPath.

**Comment by Thobov** [comment]
Thank you for your quick reply and for your help. I applied the changes you recommended in my scripts. It works fine now!
